class ProfileModel {
  final String tradingName,
      abn,
      gstRegistered,
      businessStructure,
      businessAddressLine1,
      city,
      state,
      postalCode,
      firstName,
      phoneNumber,
      otherNumber,
      email,
      website,
      trades,
      regions,
      availableEmergency,
      liabilityCompany,
      liabilityPolicyNumber,
      expiryDate,
      valueOfCover,
      certificateCurrency,
      constructionSafetyCardNumber,
      constructionSaftyCard,
      drivingLicence,
      drivingLicenceNumber,
      regulatoryBodyLicenceNumber,
      regulatoryBodyExpiryDate,
      regulatoryBodyLicence,
      workCoverPolicyNumber,
      workCoverExpiryDate,
      workCoverCertificateCurrency,
      localLegislation,
      swms,
      subbieCapabilityDocument,
      notes;

  ProfileModel({
    required this.tradingName,
    required this.abn,
    required this.gstRegistered,
    required this.businessStructure,
    required this.businessAddressLine1,
    required this.city,
    required this.state,
    required this.postalCode,
    required this.firstName,
    required this.phoneNumber,
    required this.otherNumber,
    required this.email,
    required this.website,
    required this.trades,
    required this.regions,
    required this.availableEmergency,
    required this.liabilityCompany,
    required this.liabilityPolicyNumber,
    required this.expiryDate,
    required this.valueOfCover,
    required this.certificateCurrency,
    required this.constructionSafetyCardNumber,
    required this.constructionSaftyCard,
    required this.drivingLicence,
    required this.drivingLicenceNumber,
    required this.regulatoryBodyLicenceNumber,
    required this.regulatoryBodyExpiryDate,
    required this.regulatoryBodyLicence,
    required this.workCoverPolicyNumber,
    required this.workCoverExpiryDate,
    required this.workCoverCertificateCurrency,
    required this.localLegislation,
    required this.swms,
    required this.subbieCapabilityDocument,
    required this.notes,
  });
}
